apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: compose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: compose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - name: sample-bank
          image: nikhilgoenka/samplebank-nginx:blue
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources: {}
          env:
          - name: LD_PRELOAD
            value: /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so
          - name: DT_NETWORK_ZONE
            value: <your_network_zone>
          volumeMounts:
          - mountPath: /opt/dynatrace/oneagent
            name: oneagent

# initcontainer to download OneAgent
      initContainers:
      - name: install-oneagent
        image: alpine:latest
        command:
        - /bin/sh
        args:
        - -c
        - ARCHIVE=$(mktemp) && wget -O $ARCHIVE "$DT_API_URL/v1/deployment/installer/agent/unix/paas/latest?Api-Token=$DT_PAAS_TOKEN&$DT_ONEAGENT_OPTIONS" && unzip -o -d /opt/dynatrace/oneagent $ARCHIVE && rm -f $ARCHIVE
        env:
        - name: DT_API_URL
          value: https://us.step.dynatrace.com/e/<environment-url>/api
        - name: DT_PAAS_TOKEN
          value: dt0c01.token
        - name: DT_ONEAGENT_OPTIONS
          value: flavor=default&include=all
        volumeMounts:
        - mountPath: /opt/dynatrace/oneagent
          name: oneagent

      restartPolicy: Always

      volumes:
      - name: oneagent
        emptyDir: {}
status: {}
                                                                                                                                                                                    69,1          Bot
