apiVersion: v1
kind: Service
metadata:
 name: deployment-green
 namespace: canary-deployment
 annotations:
   service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
 selector:
   run: green
 ports:
   - name: "3000"
     port: 3000
     nodePort: 30005
 type: NodePort
 #type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-green
 namespace: canary-deployment
spec:
 selector:
   matchLabels:
     run: green
 template:
   metadata:
     labels:
       run: green
       stage: production
       app.kubernetes.io/version: "green"
       app.kubernetes.io/name: "sampleBankApp"
       app.kubernetes.io/component: "frontend"
       app.kubernetes.io/part-of: "banking_application"
       
   spec:
     containers:
     - name: frontend
       image: nikhilgoenka/samplebank-nginx:green
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 3000
         protocol: TCP
